### ISSUE TITLE
Do_SPDX vs. Do_SOCS

### ISSUE THREAD

**Issue by klumb** [ttgurney/yocto-spdx#17]
Now that Matt has clarified the relationship between Do_SPDX and Do_SOCS, would we be better off just forking DoSOCS?

**Comment by ttgurney** [comment]
DoSOCS has nothing to do with Yocto (I think...), so at this point I'm not sure what benefit it would be to us to fork it. There may be some code in it we can use, though (SPDX generation logic?)
We can talk about this one in class.

**Comment by ttgurney** [comment]
Closing since we've decided to fork DoSOCS and make pull requests as needed to fix the code so we can use DoSOCS in our own project.

**Comment by germonprez** [comment]
This is fine with me. Communicate with Zac on this so that there is not
overlap on what is being fixed. Forking can be used to fix things (or used
to simply fork and differentiate). The challenge in using it to fix things
is that two minds might be thinking about the fix in two different
communities.
