### ISSUE TITLE
Installation of doSOCS

### ISSUE THREAD

**Issue by DanPatten** [ttgurney/yocto-spdx#61]
Instead of requiring the user to manually setup doSOCS, you can have it automatically clone as part of your install script. I would also mention the required dependencies needed by doSOCS including fossology and mysql.

**Comment by ttgurney** [comment]
The automatic DoSOCS setup is a solid idea and one we've been mulling over a while. It will take some thought on our part to determine the best way to do it.

Leaving out the list of DoSOCS dependencies was deliberate on my part since I considered them out of scope. Yocto+SPDX does not have dependencies on these items, only on DoSOCS itself. If the dependencies of DoSOCS change (quite possible since it is not yet production ready software) we want to be totally decoupled from that change. The rest of the team may disagree with me on this, though, so I'm hoping they weigh in.

**Comment by klumb** [comment]
After careful consideration, we have determined that keeping DoSOCS decoupled from our system is necessary.  Changes to DoSOCS have occured since the beginning of our project that would have required edits and changes to our install process if DoSOCS had been included.  By keeping them seperate we are ensuring that our install process is always up-to-date.
